FROM golang:1.5.2
MAINTAINER Gaël Gillard<gael@gaelgillard.com>

COPY ./fake_data /etc/data
COPY . /go/src/github.com/helphone/importer
WORKDIR /go/src/github.com/helphone/importer

CMD ["bash", "-c", "go test -v $(go list ./...|grep -v vendor) -race -p=1"]
