FROM alpine:3.3
MAINTAINER Gaël Gillard<gael@gaelgillard.com>

RUN apk add --update go git && \
		rm -rf /var/cache/apk/*

VOLUME ["/usr/lib/go/src/github.com/helphone/importer"]
WORKDIR /usr/lib/go/src/github.com/helphone/importer

CMD ["go", "build", "-o", "importer", "main.go"]
