FROM golang:1.6-alpine
MAINTAINER Gaël Gillard<gael@gaelgillard.com>

RUN apk add --update git && \
		rm -rf /var/cache/apk/*

VOLUME ["/go/src/github.com/helphone/importer"]
WORKDIR /go/src/github.com/helphone/importer

CMD ["go", "build", "-o", "importer", "main.go"]
